language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: linux
      compiler: clang
      sudo: false

before_install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install -y automake pkg-config libtool; fi

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
