version: 2

jobs:
  build-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: "echo 'hello osx'"

  build-linux:
    machine: true
    steps:
      - checkout
      - run: "echo 'hello linux'"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      #- build-osx
      - build-linux