language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: linux
      sudo: false

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./scripts/${MASON_NAME}/${MASON_VERSION}/test.sh
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
