language: cpp

sudo: false

matrix:
  include:
    - os: osx
      osx_image: xcode6
      compiler: clang
    - os: osx
      osx_image: xcode7
      compiler: clang
    - os: linux
      compiler: clang
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ARCH=arm
    - os: linux
      env: MASON_PLATFORM=android MASON_ANDROID_ARCH=x86

script:
- if [[ $(uname -s) == 'Darwin' ]]; then brew rm freetype || true; fi
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
