language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.2
      compiler: clang
    - os: osx
      osx_image: xcode8.2
      env: MASON_CUSTOM_ARCH=haswell
      compiler: clang
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-4.9-dev
           - xutils-dev
    - os: linux
      sudo: false
      env: MASON_CUSTOM_ARCH=core-avx-i
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-4.9-dev
           - xutils-dev
    - os: linux
      sudo: false
      env: MASON_CUSTOM_ARCH=ivybridge
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - libstdc++-4.9-dev
           - xutils-dev

script:
- ./mason build ${MASON_NAME} ${MASON_VERSION}
- ./mason publish ${MASON_NAME} ${MASON_VERSION}
